export default {
    RUNTIME_LOADED: 'RUNTIME_LOADED',

    SHOW_FLASHMESSAGE: 'SHOW_FLASHMESSAGE',
    REMOVE_FLASHMESSAGE: 'REMOVE_FLASHMESSAGE',

    MOUSE_OVER: 'MOUSE_OVER',
    MOUSE_OUT: 'MOUSE_OUT',

    LOAD_ARTICLES: 'LOAD_ARTICLES',
    LOAD_ARTICLES_SUCCESS: 'LOAD_ARTICLES_SUCCESS',
    LOAD_ARTICLES_ERROR: 'LOAD_ARTICLES_ERROR',

    LOGOUT: 'LOGOUT',

    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_STARTED: 'REGISTER_STARTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    UPDATE: 'UPDATE',
    UPDATE_AVATAR: 'UPDATE_AVATAR',

    USER_GET_INFO_SUCCESS: 'USER_GET_INFO_SUCCESS'
}
